services:
  app:
    container_name: next16-app-react19-ts-headless
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=http://api:8080/api/v1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge